@host = http://localhost:8080

### auth
POST {{host}}/api/auth
Content-Type: application/json

{
  "email": "your@email.com",
  "pass": "your-password"
}

> {%
const body = JSON.parse(response.body)
client.global.set('token', body.token)
%}

### get user
GET {{host}}/api/user
Authorization: Bearer {{token}}